<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'error-aria-label' => 'Произошла ошибка, пожалуйста, попробуйте еще раз',
    'error-label' => 'Ошибка. Попробуйте еще раз.',
    'initial-state' => 'Подтвердите, что вы человек',
    'solved-label' => 'Проверка пройдена',
    'troubleshooting-label' => 'Поиск и устранение неисправностей',
    'verified-aria-label' => 'Мы подтвердили, что вы человек, теперь вы можете продолжить',
    'verify-aria-label' => 'Нажмите, чтобы подтвердить, что вы человек',
    'verifying-aria-label' => 'Проверка того, что вы человек, пожалуйста, подождите',
    'verifying-label' => 'Проверка...',
    'wasm-disabled' => 'Включите WASM для более быстрого решения',
];
