<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'error-aria-label' => 'An error occurred, please try again',
    'error-label' => 'Error. Try again.',
    'initial-state' => 'Verify you\'re human',
    'solved-label' => 'You\'re a human',
    'troubleshooting-label' => 'Troubleshoot',
    'verified-aria-label' => 'We have verified you\'re a human, you may now continue',
    'verify-aria-label' => 'Click to verify you\'re a human',
    'verifying-aria-label' => 'Verifying you\'re a human, please wait',
    'verifying-label' => 'Verifying...',
    'wasm-disabled' => 'Enable WASM for significantly faster solving',
];
